Generate treasury report for Project 1C
usdigitalresponse/cpf-reporter pull request #338
Opened 2024-06-17 16:49 UTC by vshia

Ticket: https://github.com/usdigitalresponse/cpf-reporter/issues/317

2024-06-24 16:06 UTC, as1729 commented on python/src/schemas/schema_V2024_05_24.py
> +                "output_column_1A": "E",
can we name this `treasury_report_col_1A` `treasury_report_col_1B` and `treasury_report_col_1C`?

2024-06-24 16:07 UTC, as1729 commented
@vshia it would be great if we can merge the changes in the schema `python/src/schemas/schema_V2024_05_24.py` as they look good. Are you able to open a separate PR with just those changes?

2024-06-24 17:38 UTC, vshia commented
@as1729 Unfortunately, I think it'll be hard to extract just the schema changes. There have been alot of lint changes which may result in alot of conflicts.

2024-07-12 15:55 UTC, as1729 commented
@vshia one thing we would need here before we are ready to merge is the terraform changes to add the new lambda function.

You'll need to add a separate module called `lambda_function-<function_name>` similar to the pattern here: https://github.com/usdigitalresponse/cpf-reporter/blob/main/terraform/functions.tf#L445

The function will need to have permissions to retrieve the appropriate upload files from S3 as well as upload `.csv` files into s3. The pattern should be already available by looking at the module.

Let me know if you run into any issues adding that code.

2024-07-19 20:03 UTC, laurelkorwin approved these changes

2024-07-24 15:34 UTC, as1729 requested changes
Small change requested to remove `{user.id}/` prefix wherever it exists as it is no longer needed.

2024-07-24 15:34 UTC, as1729 commented on python/src/functions/generate_treasury_report.py
> +            f"treasuryreports/{organization_id}/{current_reporting_period_id}/{user.id}",
@vshia one-small change here. Can we remove the `/{user.id}` prefix? The reports should be saved on the reporting period level and not be user-specific.

Apologies for not communicating this design change earlier. The change was made to ensure that the treasury report is the same regardless of who the user is for the entire organization.

2024-07-24 17:52 UTC, as1729 approved these changes

2024-07-24 17:55 UTC, merged